# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: chain-bench
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: cmd/chain-bench/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    binary: chain-bench
release:
  discussion_category_name: Announcements

archives:
  - id: archive
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "openbsd" }}OpenBSD
      {{- else if eq .Os "netbsd" }}NetBSD
      {{- else if eq .Os "freebsd" }}FreeBSD
      {{- else if eq .Os "dragonfly" }}DragonFlyBSD
      {{- else}}{{- .Os }}{{ end }}-
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "arm" }}ARM
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else if eq .Arch "ppc64le" }}PPC64LE
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
      - templates/*.tpl

brews:
  - 
    tap:
      owner: aquasecurity
      name: homebrew-chain-bench
    homepage: "https://github.com/aquasecurity/chain-bench"
    description: "Chain-bench is an open-source tool for auditing your software supply chain stack for security compliance based on a new CIS Software Supply Chain benchmark"

dockers:
  - image_templates:
      - "{{ .Env.DOCKERHUB_PATH }}/chain-bench:{{ .Version }}-amd64"
      - "{{ .Env.DOCKERHUB_PATH }}/chain-bench:latest-amd64"
      - "{{ .Env.GHCR_PATH }}/chain-bench:{{ .Version }}-amd64"
      - "{{ .Env.GHCR_PATH }}/chain-bench:latest-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    ids:
      - chain-bench
    build_flag_templates: 
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Chain-bench is an open-source tool for auditing your software supply chain stack for security compliance based on a new CIS Software Supply Chain benchmark"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/chain-bench"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.url=https://github.com/aquasecurity/chain-bench"
      - "--label=org.opencontainers.image.documentation=https://github.com/aquasecurity/chain-bench"
      - "--platform=linux/amd64"
    extra_files:
    - templates/
  - image_templates:
      - "{{ .Env.DOCKERHUB_PATH }}/chain-bench:{{ .Version }}-arm64"
      - "{{ .Env.DOCKERHUB_PATH }}/chain-bench:latest-arm64"
      - "{{ .Env.GHCR_PATH }}/chain-bench:{{ .Version }}-arm64"
      - "{{ .Env.GHCR_PATH }}/chain-bench:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    ids:
      - chain-bench
    build_flag_templates: 
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=Chain-bench is an open-source tool for auditing your software supply chain stack for security compliance based on a new CIS Software Supply Chain benchmark"
      - "--label=org.opencontainers.image.vendor=Aqua Security"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/aquasecurity/chain-bench"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.url=https://github.com/aquasecurity/chain-bench"
      - "--label=org.opencontainers.image.documentation=https://github.com/aquasecurity/chain-bench"
      - "--platform=linux/arm64"
    extra_files:
    - templates/

docker_manifests:
  - name_template: '{{ .Env.DOCKERHUB_PATH }}/chain-bench:{{ .Version }}'
    image_templates: &dockerhub_image_templates
      - '{{ .Env.DOCKERHUB_PATH }}/chain-bench:{{ .Version }}-amd64'
      - '{{ .Env.DOCKERHUB_PATH }}/chain-bench:{{ .Version }}-arm64'
  - name_template: '{{ .Env.GHCR_PATH }}/chain-bench:{{ .Version }}'
    image_templates: &ghcr_image_templates
      - '{{ .Env.GHCR_PATH }}/chain-bench:{{ .Version }}-amd64'
      - '{{ .Env.GHCR_PATH }}/chain-bench:{{ .Version }}-arm64'
  - name_template: '{{ .Env.DOCKERHUB_PATH }}/chain-bench:latest'
    image_templates: *dockerhub_image_templates
  - name_template: '{{ .Env.GHCR_PATH }}/chain-bench:latest'
    image_templates: *ghcr_image_templates



checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
