site_name: Chain-bench
site_url: https://aquasecurity.github.io/chain-bench/
site_description: An open-source tool for auditing your software supply chain stack for security compliance based on a new CIS Software Supply Chain benchmarks
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/aquasecurity/chain-bench
edit_uri: ""

nav:
  - HOME: index.md
  - Getting started:
      - Quick Start: getting-started/quickstart.md
      - Installation: getting-started/installation.md
theme:
  name: material
  language: "en"
  # TODO: replace with svg
  logo: imgs/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - footnotes
  - attr_list
  - pymdownx.tabbed
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  generator: false
  version:
    method: mike
    provider: mike
  var:
    prev_git_tag: "v0.0.0"
    operator_version: "v0.0.7"

plugins:
  - search
  - macros
