name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Configure Git URL
        run: |
          git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build
        run: |
          make

      - name: Execute Tests with Coverage
        run: |
          make test-coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
